services:
  workerr209-frontend:
    container_name: workerr209-frontend
    image: nginx:alpine
    ports:
      - '4200:4200'
    restart: unless-stopped
    volumes:
      - /mnt/HikvisionSSD1024/docker-data/workerr209/frontend/html:/usr/share/nginx/html:ro
      - /mnt/HikvisionSSD1024/docker-data/workerr209/frontend/conf/default.conf:/etc/nginx/conf.d/default.conf:ro